#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

# udevd uses unix domain sockets for communication
force_load unix

copy_exec /sbin/udevd      /sbin
copy_exec /sbin/udevadm    /sbin

mkdir -p $DESTDIR/etc/udev
cp -a /etc/udev/*.conf $DESTDIR/etc/udev/

mkdir -p $DESTDIR/lib/udev/rules.d
for rules in 30-kernel-compat.rules 50-firmware.rules 50-udev-default.rules \
	60-cdrom_id.rules 60-floppy.rules 60-persistent-input.rules \
	60-persistent-storage.rules 61-persistent-storage-edd.rules \
	80-drivers.rules 64-device-mapper.rules ; do
	cp -a "$f" $DESTDIR/lib/udev/rules.d/
  if   [ -e /etc/udev/rules.d/$rules ]; then
    cp -p /etc/udev/rules.d/$rules $DESTDIR/lib/udev/rules.d/
  elif [ -e /lib/udev/rules.d/$rules ]; then
    cp -p /lib/udev/rules.d/$rules $DESTDIR/lib/udev/rules.d/
  fi
done

for program in /lib/udev/*_id; do
  copy_exec $program /lib/udev
done

copy_exec /sbin/blkid /sbin
