#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

# udevd uses unix domain sockets for communication
force_load unix

cp -a /etc/udev/ $DESTDIR/etc/
rm -f $DESTDIR/etc/udev/rules.d/75-cd-aliases-generator.rules
if [ -e /etc/scsi_id.config ]; then
  cp /etc/scsi_id.config $DESTDIR/etc/
fi

copy_exec /sbin/udevd      /sbin
copy_exec /sbin/udevadm    /sbin

mkdir -p $DESTDIR/lib/udev/
for program in /lib/udev/*_id; do
  copy_exec $program /lib/udev
done
