#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

# udevd uses unix domain sockets for communication
force_load unix

mkdir -p $DESTDIR/etc/udev/rules.d
cp -a /etc/udev/*.conf $DESTDIR/etc/udev/
for f in /etc/udev/rules.d/*device-mapper* ; do
	cp -a "$f" $DESTDIR/etc/udev/rules.d/
done

if [ -e /etc/scsi_id.config ]; then
  cp /etc/scsi_id.config $DESTDIR/etc/
fi

copy_exec /sbin/udevd      /sbin
copy_exec /sbin/udevadm    /sbin

mkdir -p $DESTDIR/lib/udev/rules.d
cp -a /lib/udev/rules.d/* $DESTDIR/lib/udev/rules.d/
rm -f $DESTDIR/etc/udev/rules.d/75-cd-aliases-generator.rules

for program in /lib/udev/*_id; do
  copy_exec $program /lib/udev
done

# udev README says:
# - The system must have the following group names resolvable at udev startup:
#     disk, cdrom, floppy, tape, audio, video, lp, tty, dialout, kmem
egrep '^(disk|cdrom|floppy|tape|audio|video|lp|tty|dialout|kmem):' /etc/group > $DESTDIR/etc/group
